[enh] Use new helpers and download sources

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -1,41 +1,37 @@
 #!/bin/bash
-APP=${!#}
 
 set -e
 
-APPNAME=`echo -n own;echo 'cloud'`
-SOURCES=`echo -n $APPNAME;echo '-8.2.2'`
+# App instance id
+APP=${!#}
 
 # Retrieve arguments
 domain=$1
-path=$2
+path=${2%/}
 user=$3
 
-# Check user parameter
-sudo yunohost user list --json | grep -qi "\"username\": \"$user\"" \
-	|| (echo "User does not exist: $user" && exit 1)
-sudo yunohost app setting $APP admin_user -v $user
+# Load common variables
+. ./_common.sh
 
-# Check domain/path availability
-sudo yunohost app checkurl $domain$path -a $APP \
-	|| (echo "Path not available: $domain$path" && exit 1)
-
-# Remove trailing "/" for next commands
-path=${path%/}
-
-# Install dependencies
-sudo apt-get update -qq
-sudo DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confdef" -y --force-yes -qq install acl smbclient php5-cli php-apc coreutils gnupg tar
-
-# Generate random password
-db_pwd=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d 'A-Za-z0-9' | sed -n 's/\(.\{24\}\).*/\1/p')
-
-# Use 'owncloud' as database name and user
+# Set app specific variables
+db_name=$APP
 db_user=$APP
 
-# Initialize database and store mysql password for upgrade
-sudo yunohost app initdb $db_user -p $db_pwd
-sudo yunohost app setting $APP mysqlpwd -v $db_pwd
+# Source app helpers
+. /usr/share/yunohost/helpers
+
+# TODO: Check domain/path availability with app helper
+sudo yunohost app checkurl $domain$path -a $APP \
+  || die "The path ${domain}${path} is not available for app installation."
+
+# Check user parameter
+ynh_user_exists "$user" \
+  || die "The chosen admin user does not exist."
+sudo yunohost app setting $APP admin_user -v $user
+
+# Install dependencies
+ynh_package_install_from_equivs ../conf/${DEPS_PKG_NAME}.control \
+  || die "Unable to install dependencies"
 
 # Delete db and user if exit with an error
 function exit_properly
@@ -53,23 +49,36 @@ function exit_properly
 }
 trap exit_properly ERR
 
+# Generate random password
+db_pwd=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d 'A-Za-z0-9' | sed -n 's/\(.\{24\}\).*/\1/p')
+
+# Initialize database and store mysql password for upgrade
+sudo yunohost app initdb $db_user -p $db_pwd
+sudo yunohost app setting $APP mysqlpwd -v $db_pwd
+
 # Create owncloud user
 sudo useradd -d /var/www/$APP $APP \
 	|| exit_properly
 
-# Verify sources and extract it
-sha256sum --strict --quiet -c ../sources/$SOURCES.tar.bz2.sha256sum < ../sources/$SOURCES.tar.bz2
-gpg --import ../sources/$APPNAME.asc
-gpg --verify ../sources/$SOURCES.tar.bz2.asc ../sources/$SOURCES.tar.bz2
-sudo mkdir -p ../tmp/
-sudo tar -jxf ../sources/$SOURCES.tar.bz2 -C ../tmp/
+# Verify sources and extract it in a tmp directory
+TMPDIR=$(ynh_mkdir_tmp)
+# FIXME: need real name for checksum
+oc_tarball="owncloud-${VERSION}.tar.bz2"
+(cd "$TMPDIR" \
+ && wget -q -O "${oc_tarball}" ${OWNCLOUD_SOURCE_URL} \
+ && wget -q -O "${oc_tarball}.sha256" ${OWNCLOUD_CHECKSUM_URL} \
+ && sha256sum --strict --quiet -c "${oc_tarball}.sha256" < $oc_tarball) \
+  || die "Unable to download and verify ownCloud tarball"
+#gpg --import ../sources/$APPNAME.asc
+#gpg --verify ../sources/$SOURCES.tar.bz2.asc ../sources/$SOURCES.tar.bz2
+tar -jxf "${TMPDIR}/${oc_tarball}" -C "$TMPDIR"
 
 # Copy files to the right place
 final_path=/var/www/$APP
 data_path=/home/yunohost.app/$APP/data
 sudo mkdir -p $final_path
 sudo mkdir -p $data_path
-sudo cp -a ../tmp/$APPNAME/. $final_path/
+sudo cp -a ${TMPDIR}/${APPNAME}/. ${final_path}/
 sudo cp -a ../conf/ow-setup $final_path/ow-setup
 sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$APP.conf
 sudo cp ../conf/php-fpm.conf /etc/php5/fpm/pool.d/$APP.conf
@@ -84,6 +93,9 @@ sudo chmod 755 /home/yunohost.app
 sudo chmod -R u=rwX,g=rwX,o=rX $final_path
 sudo chmod -R u=rwX,g=rwX,o= $data_path
 
+# Remove tmp directory
+rm -rf "$TMPDIR"
+
 # Needed for Jessie/PHP5.6 compatibility
 sudo sed -i "s/;always_populate_raw/always_populate_raw/" /etc/php5/cli/php.ini
 
@@ -91,7 +103,7 @@ sudo sed -i "s/;always_populate_raw/always_populate_raw/" /etc/php5/cli/php.ini
 if [[ "$path" == "" ]]; then
     sudo sed -i "s@LOCATIONTOCHANGE@/@g" /etc/nginx/conf.d/$domain.d/$APP.conf
 else
-	sudo sed -i "s@LOCATIONTOCHANGE@$path@g" /etc/nginx/conf.d/$domain.d/$APP.conf
+    sudo sed -i "s@LOCATIONTOCHANGE@$path@g" /etc/nginx/conf.d/$domain.d/$APP.conf
 fi
 sudo sed -i "s@PATHTOCHANGE@$path@g" /etc/nginx/conf.d/$domain.d/$APP.conf
 sudo sed -i "s@ALIASTOCHANGE@$final_path/@g" /etc/nginx/conf.d/$domain.d/$APP.conf
@@ -126,7 +138,7 @@ cd $old_pwd
 
 # Check if the Mysql database is initialized & running
 sleep 2
-mysql -u $db_user -p$db_pwd $db_user -e "select * from oc_appconfig;" > /dev/null 2>&1 \
+mysql -u $db_user -p$db_pwd $db_name -e "select * from oc_appconfig;" > /dev/null 2>&1 \
     || (echo "Owncloud is not properly installed" && exit_properly)
 
 # Enable plugins
@@ -176,7 +188,7 @@ sudo find $final_path -type d -print0 | xargs -0 sudo chmod 775 \
 sudo chmod -R 770 $data_path
 
 # Make an LDAP user as admin
-mysql -u $db_user -p$db_pwd $db_user -e "INSERT INTO oc_group_user VALUES ('admin','$user');"
+mysql -u $db_user -p$db_pwd $db_name -e "INSERT INTO oc_group_user VALUES ('admin','$user');"
 
 #Configure cache
 if ! grep -Fq "memcache" $final_path/config/config.php
